/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.wirespeed.clinic.api;

import com.wirespeed.clinic.model.Appointment;
import com.wirespeed.clinic.model.AppointmentStatus;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import java.util.List;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-19T00:09:17.180339900-04:00[America/New_York]", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "Appointments", description = "the Appointments API")
public interface AppointmentsApi {

    /**
     * GET /appointments : Get appointments with optional filtering
     *
     * @param providerId Filter for assigned appointments (optional)
     * @param status  (optional)
     * @return List of appointments (status code 200)
     */
    @Operation(
        operationId = "appointmentsGet",
        summary = "Get appointments with optional filtering",
        tags = { "Appointments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of appointments", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Appointment.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/appointments",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Appointment>> appointmentsGet(
        @Parameter(name = "providerId", description = "Filter for assigned appointments", in = ParameterIn.QUERY) @Valid @RequestParam(value = "providerId", required = false) Integer providerId,
        @Parameter(name = "status", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) AppointmentStatus status
    );


    /**
     * GET /appointments/{id} : Get a specific appointment
     *
     * @param id  (required)
     * @return Appointment details (status code 200)
     */
    @Operation(
        operationId = "appointmentsIdGet",
        summary = "Get a specific appointment",
        tags = { "Appointments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Appointment details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Appointment.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/appointments/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Appointment> appointmentsIdGet(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    /**
     * POST /appointments : Schedule a new appointment
     *
     * @param appointment  (optional)
     * @return Appointment scheduled (status code 201)
     */
    @Operation(
        operationId = "appointmentsPost",
        summary = "Schedule a new appointment",
        tags = { "Appointments" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Appointment scheduled")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/appointments",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> appointmentsPost(
        @Parameter(name = "Appointment", description = "") @Valid @RequestBody(required = false) Appointment appointment
    );


    /**
     * PUT /appointments/{id} : Update an existing appointment
     *
     * @param id  (required)
     * @param appointment  (optional)
     * @return Appointment updated successfully (status code 200)
     */
    @Operation(
        operationId = "appointmentsIdPut",
        summary = "Update an existing appointment",
        tags = { "Appointments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Appointment updated successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/appointments/{id}",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> appointmentsIdPut(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "Appointment", description = "") @Valid @RequestBody(required = false) Appointment appointment
    );


    /**
     * DELETE /appointments/{id} : Delete an appointment
     *
     * @param id  (required)
     * @return Appointment deleted successfully (status code 204)
     */
    @Operation(
        operationId = "appointmentsIdDelete",
        summary = "Delete an appointment",
        tags = { "Appointments" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Appointment deleted successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/appointments/{id}"
    )
    
    ResponseEntity<Void> appointmentsIdDelete(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );

}
