/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.wirespeed.clinic.api;

import com.wirespeed.clinic.model.Appointment;
import com.wirespeed.clinic.model.Patient;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import java.util.List;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-19T00:09:17.180339900-04:00[America/New_York]", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "Patients", description = "the Patients API")
public interface PatientsApi {

    /**
     * GET /patients : Get all patients
     *
     * @return List of patients (status code 200)
     */
    @Operation(
        operationId = "patientsGet",
        summary = "Get all patients",
        tags = { "Patients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of patients", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Patient.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/patients",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Patient>> patientsGet(
        
    );


    /**
     * GET /patients/{id} : Get a specific patient
     *
     * @param id  (required)
     * @return Patient details (status code 200)
     */
    @Operation(
        operationId = "patientsIdGet",
        summary = "Get a specific patient",
        tags = { "Patients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Patient details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Patient.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/patients/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Patient> patientsIdGet(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    /**
     * GET /patients/{id}/appointments : View personal appointment history for a specific patient
     *
     * @param id  (required)
     * @return Patient appointment history (status code 200)
     */
    @Operation(
        operationId = "patientsIdAppointmentsGet",
        summary = "View personal appointment history for a specific patient",
        tags = { "Patients", "Appointments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Patient appointment history", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Appointment.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/patients/{id}/appointments",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Appointment>> patientsIdAppointmentsGet(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    /**
     * PUT /patients/{id} : Update an existing patient profile
     *
     * @param id  (required)
     * @param patient  (optional)
     * @return Patient updated (status code 200)
     */
    @Operation(
        operationId = "patientsIdPut",
        summary = "Update an existing patient profile",
        tags = { "Patients" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Patient updated")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/patients/{id}",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> patientsIdPut(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "Patient", description = "") @Valid @RequestBody(required = false) Patient patient
    );


    /**
     * DELETE /patients/{id} : Delete a patient profile
     *
     * @param id  (required)
     * @return Patient deleted (status code 204)
     */
    @Operation(
        operationId = "patientsIdDelete",
        summary = "Delete a patient profile",
        tags = { "Patients" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Patient deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/patients/{id}"
    )
    
    ResponseEntity<Void> patientsIdDelete(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    /**
     * POST /patients : Create new patient profile
     *
     * @param patient  (optional)
     * @return Patient created (status code 201)
     */
    @Operation(
        operationId = "patientsPost",
        summary = "Create new patient profile",
        tags = { "Patients" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Patient created")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/patients",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> patientsPost(
        @Parameter(name = "Patient", description = "") @Valid @RequestBody(required = false) Patient patient
    );

}
