/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.wirespeed.clinic.api;

import com.wirespeed.clinic.model.Provider;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import jakarta.validation.Valid;
import java.util.List;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-04-19T00:09:17.180339900-04:00[America/New_York]", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "Providers", description = "the Providers API")
public interface ProvidersApi {

    /**
     * GET /providers : Get all providers
     *
     * @return List of providers (status code 200)
     */
    @Operation(
        operationId = "providersGet",
        summary = "Get all providers",
        tags = { "Providers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of providers", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Provider.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/providers",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Provider>> providersGet(
        
    );


    /**
     * GET /providers/{id} : Get a specific provider
     *
     * @param id  (required)
     * @return Provider details (status code 200)
     */
    @Operation(
        operationId = "providersIdGet",
        summary = "Get a specific provider",
        tags = { "Providers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Provider details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Provider.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/providers/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Provider> providersIdGet(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    /**
     * PUT /providers/{id} : Update an existing healthcare provider
     *
     * @param id  (required)
     * @param provider  (optional)
     * @return Provider updated (status code 200)
     *         or Unprocessable Entity - NPI validation failed (status code 422)
     */
    @Operation(
        operationId = "providersIdPut",
        summary = "Update an existing healthcare provider",
        tags = { "Providers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Provider updated"),
            @ApiResponse(responseCode = "422", description = "Unprocessable Entity - NPI validation failed")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/providers/{id}",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> providersIdPut(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id,
        @Parameter(name = "Provider", description = "") @Valid @RequestBody(required = false) Provider provider
    );


    /**
     * DELETE /providers/{id} : Delete a healthcare provider
     *
     * @param id  (required)
     * @return Provider deleted (status code 204)
     */
    @Operation(
        operationId = "providersIdDelete",
        summary = "Delete a healthcare provider",
        tags = { "Providers" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Provider deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/providers/{id}"
    )
    
    ResponseEntity<Void> providersIdDelete(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    );


    /**
     * POST /providers : Register a healthcare provider with NPI validation
     *
     * @param provider  (optional)
     * @return Provider registered (status code 201)
     *         or Unprocessable Entity - NPI validation failed (status code 422)
     */
    @Operation(
        operationId = "providersPost",
        summary = "Register a healthcare provider with NPI validation",
        tags = { "Providers" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Provider registered"),
            @ApiResponse(responseCode = "422", description = "Unprocessable Entity - NPI validation failed")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/providers",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> providersPost(
        @Parameter(name = "Provider", description = "") @Valid @RequestBody(required = false) Provider provider
    );

}
