# JWT secret
jwt_secret=ClinicConnectVerySecretJWTKey

# H2 in-memory datasource
spring.datasource.url=jdbc:h2:mem:clinicdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.datasource.username=sa
spring.datasource.password=

# Application name
spring.application.name=clinic-connect-server

# Base path for all API endpoints
server.servlet.context-path=/api

# H2 Console (dev convenience)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
